services:

  echo-hub:
    build:
      context: ./
      dockerfile: ./echo-hub/Dockerfile
    container_name: echo-hub
    command: go run .
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/
    working_dir: /go/src/echo-hub
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/echo-vision?sslmode=disable
      DATABASE_SCHEMA: echo_hub
      RABBITMQ_URL: amqp://guest:guest@vision-rabbitmq/
      JWT_SECRET: whatever

  postgres:
    image: postgres:12.0-alpine
    container_name: echo-vision-db
    environment:
      POSTGRES_DB: echo-vision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-vision-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: vision-rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: "1.0"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-vision-data:
  rabbitmq_etc:
    labels:
      description: "RabbitMQ configuration"
  rabbitmq_data:
    labels:
      description: "RabbitMQ data"
  rabbitmq_logs:
    labels:
      description: "RabbitMQ logs"
