services:
  # echo-ui:
  #   build: ./echo-ui
  #   container_name: echo-ui
  #   volumes:
  #     - ./echo-ui:/app
  #     - ./echo-ui/node_modules:/app/node_modules
  #   ports:
  #     - 3000:80
  #   environment:
  #     NODE_ENV: development
  #     PORT: 80
  #   command: sh -c "pnpm install && pnpm dev"

  echo-hub:
    build:
      context: ./
      dockerfile: ./echo-hub/Dockerfile
    container_name: echo-hub
    command: go run .
    ports:
      - 8000:80
    volumes:
      - .:/go/src/
    working_dir: /go/src/echo-hub
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/echo-vision?sslmode=disable
      DATABASE_SCHEMA: echo_hub
      RABBITMQ_URL: amqp://guest:guest@vision-rabbitmq/
      JWT_SECRET: whatever
      AWS_REGION: us-east-2
      AWS_BUCKET_NAME: echo-vision-local
    env_file:
      - .env

  echo-analyzer:
    build:
      context: ./
      dockerfile: ./echo-analyzer/Dockerfile
    container_name: echo-analyzer
    command: go run .
    volumes:
      - .:/go/src/
    working_dir: /go/src/echo-analyzer
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/echo-vision?sslmode=disable
      DATABASE_SCHEMA: echo_analyzer
      RABBITMQ_URL: amqp://guest:guest@vision-rabbitmq/
      AWS_REGION: us-east-2
      AWS_BUCKET_NAME: echo-vision-local
    env_file:
      - .env

  postgres:
    image: postgres:12.0-alpine
    container_name: echo-vision-db
    environment:
      POSTGRES_DB: echo-vision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-vision-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: vision-rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: "1.0"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: echo-sentinel
    volumes:
      - ./echo-sentinel/nginx.conf:/etc/nginx/nginx.conf
      - ./echo-sentinel/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - echo-hub:echo-hub

    networks:
      default:
        aliases:
          - echo-vision.local

volumes:
  postgres-vision-data:
  rabbitmq_etc:
    labels:
      description: "RabbitMQ configuration"
  rabbitmq_data:
    labels:
      description: "RabbitMQ data"
  rabbitmq_logs:
    labels:
      description: "RabbitMQ logs"
